# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('stockXL', models.IntegerField(default=0)),
                ('stockL', models.IntegerField(default=0)),
                ('stockM', models.IntegerField(default=0)),
                ('stockS', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_selection', models.CharField(choices=[('m', 'MENS'), ('w', 'WOMENS')], default='m', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Sex'),
        ),
    ]
