# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='/static/catalog/images/Placeholder.jpg', max_length=1000),
        ),
    ]
