# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 18:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
